[theme]
base = "light"
primaryColor = "#990033"
borderColor = "brown"
secondaryBackgroundColor = "#f2d9d9"
backgroundColor = "Snow"

[client]
showErrorDetails = "none"
toolbarMode = "minimal"
showSidebarNavigation = false

#[theme.sidebar]
#secondaryBackgroundColor = "#99d6ff"
#primaryColor = "blue"
#textColor = "black"