[theme]
base = "light"
primaryColor = "#993333"
borderColor = "brown"
secondaryBackgroundColor = "#f2d9d9"
backgroundColor = "Snow"

[client]
showErrorDetails = "none"
toolbarMode = "minimal"
showSidebarNavigation = false

[theme.sidebar]
textColor = "black"
primaryColor = "#990033"
backgroundColor = "WhiteSmoke"
secondaryBackgroundColor = "white"